### ISSUE TITLE
Neuralynx Header Error

### ISSUE THREAD

**Issue by dneophytou** [NeuralEnsemble/python-neo#1104]
I am trying to import neuralynx data into python using neo. The code I'm running is: 
import neo
dirname = (specify directory name)
reader = neo.io.NeuralynxIO(dirname = dirname, filename = (file name in directory))

The error I am getting is "OSError: No matching header open date/time for application {} version Cheetah. Please contact developers."

**Comment by samuelgarcia** [comment]
Hi,
did you try with the new matser ?

**Comment by dneophytou** [comment]
Hello,
Yea I updated the package and am using the latest version. I had previously tried these commands with the older version and it didn’t work, and so I saw another post on GitHub where the suggestion was to update the software. I am still having the same issue since updating.
________________________________
From: Garcia Samuel ***@***.***>
Sent: Tuesday, March 22, 2022 4:01:46 AM
To: NeuralEnsemble/python-neo ***@***.***>
Cc: Demetrios Neophytou ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [NeuralEnsemble/python-neo] Neuralynx Header Error (Issue #1104)


Hi,
did you try with the new matser ?

**Comment by JuliaSprenger** [comment]
Hi @dneophytou Can you provide a small test file, so I can check which Cheetah version and header layout you are using? You can provide a file here without making it publicly accessible https://amubox.univ-amu.fr/s/5Cd2BedrfJs9BQf

**Comment by dneophytou** [comment]
I have provided a file via that link. The file is titled with my username at the beginning of the file name. Please let me know if you need anything else.

**Comment by dneophytou** [comment]
> Hi @dneophytou Can you provide a small test file, so I can check which Cheetah version and header layout you are using? You can provide a file here without making it publicly accessible https://amubox.univ-amu.fr/s/5Cd2BedrfJs9BQf

I've already uploaded a sample file, but I've just also uploaded a screenshot of the exact error message I am getting. Not sure if that'll be anymore help, but wanted to include it just in case there's an error that I'm missing.

**Comment by JuliaSprenger** [comment]
I opened a PR here https://github.com/NeuralEnsemble/python-neo/pull/1107 that should fix this issue. Can you confirm?

**Comment by dneophytou** [comment]
Hi Julia, yes this worked! Thank you so much for your help!

**Comment by redagavin** [comment]
I encountered the same issue today. This is a screenshot of the error.
![Screen Shot 2022-11-27 at 5 07 43 PM](https://user-images.githubusercontent.com/39891180/204162273-7ef68c45-302c-4e80-bfd6-bac6da9e915b.png)

Also, I noticed that there is a small bug in the line that raise the OSError. I think `.format(an, av)` is supposed to fill the first {} with `an` and the second {} with `av`. However, only the second string after the `+` calls `.format(an, av)` in the source code, which is why the error message is weird.
<img width="800" alt="Screen Shot 2022-11-27 at 5 19 11 PM" src="https://user-images.githubusercontent.com/39891180/204162647-a07972fd-f759-4677-8209-702cb060a4aa.png">
