### ISSUE TITLE
No HDF5 conversion

### ISSUE THREAD

**Issue by vonaviv** [NeuralEnsemble/python-neo#1359]
**Which page is the problem on?**

https://neo.readthedocs.io/en/stable/io.html

 `3. for reading/writing Neo structure in neutral formats (HDF5, .mat, …) but with Neo structure inside (NeoHDF5, NeoMatlab, …)`

**What is the problem?**
The documentation says I can covert to HDF5, but there is not such functionality in neo.io (or I guess it was removed earlier)

**Suggestions for fixing the problem**
Remove the mentioning of HDF5 or better let people know explicitly that there is no such function.

**Comment by apdavison** [comment]
The problem here is that the "stable" tag on readthedocs is still showing an old version of the documentation (there is a confusing error when it tries to re-build "stable").

This misleading information is missing from the latest version of the documentation: https://neo.readthedocs.io/en/latest/

By the way, if you'd like to write to HDF5 with Neo, you have two options: NixIO and NWBIO - see https://neo.readthedocs.io/en/latest/share_data.html
