### ISSUE TITLE
test_get_io_non_existant_file_writable_io: OSError: Could not identify IO for non_existant_file.nix

### ISSUE THREAD

**Issue by emollier** [NeuralEnsemble/python-neo#1409]
Greetings,

**Describe the bug**
When trying to integrate the new neo version 0.13.0 into Debian sid, I observe the following test error:
```
    def test_get_io_non_existant_file_writable_io():
        # use nixio for testing with writable io
        non_existant_file = Path("non_existant_file.nix")
        non_existant_file.unlink(missing_ok=True)
>       io = get_io(non_existant_file)

neo/test/iotest/test_get_io.py:36: 
__ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_or_folder = PosixPath('non_existant_file.nix'), args = (), kwargs = {}, ios = [<class 'neo.io.nixio.NixIO'>, <class 'neo.io.nixio_fr.NixIO'>]
io = <class 'neo.io.nixio_fr.NixIO'>

    def get_io(file_or_folder, *args, **kwargs):
        """
        Return a Neo IO instance, guessing the type based on the filename suffix.
        """
        ios = list_candidate_ios(file_or_folder)
        for io in ios:
            try:
                return io(file_or_folder, *args, **kwargs)
            except:
                continue
    
>       raise IOError(f"Could not identify IO for {file_or_folder}")
E       OSError: Could not identify IO for non_existant_file.nix

neo/io/__init__.py:426: OSError
```

**To Reproduce**
I am running the test suite using:
```bash
NOSETESTS_NO_NETWORK=1 python3.12 -m pytest -v neo
```

**Expected behaviour**
I would have expected all tests to pass, be skipped or have expected failures marked as such.  :)

**Environment:**
 - OS: Debian sid
 - Python 3.12
 - Neo 0.13.0
 - NumPy 1.24.2

Have a nice day,  :)
Étienne.

**Comment by zm711** [comment]
@emollier,

Thanks for reporting. (and hope you're having a nice day too!)

So we are still trying to work on the no-network test framework (see #1263). I'll try to raise the priority of this since this has come up a couple times now.

Second this failure is due to the fact that this test requires a `pip install nixio`. If you want to make sure all tests pass (minus the issue with network-which we need to fix) you need to `pip install neo[test]`. 

https://github.com/NeuralEnsemble/python-neo/blob/0c175b4ece81cc588971a02069af5d87e91f9cb6/pyproject.toml#L47-L69

That being said I suppose we could flag this test so that if the user doesn't have `nixio` we don't run this test. I can draft a PR and see what the others think.

Cheers,
Zach

**Comment by emollier** [comment]
Hi Zach,

Thanks for the explanation, the initial error didn't make it obvious that it was caused by missing nixio.  I'll keep a tab to get this module available as a Debian package to resolve this.

Cheers,  :)
Étienne.

**Comment by emollier** [comment]
Making the nixio module available to the test environment resolved the issue; I close the entry.
