### ISSUE TITLE
rawio missing AlphaOmega implementation.

### ISSUE THREAD

**Issue by cboulay** [NeuralEnsemble/python-neo#414]
@samuelgarcia

**Comment by samuelgarcia** [comment]
neo.io.AlphaomegaIO was started long time by me but it was more or less a draft.

Them, Florent Jaillet tried to improved the code but did not finish because there was too many diffrent specifications and version fo alphaomega for the same format. Futhermore AlphaOmega did not provide clear specification documents to him.

So actual neo.io.AlphaomegaIO is not really reliable (even it should work in some cases), I think.
So porting it in it current state to rawio API is useless and painfull.

But with:
  * clear specification from AlphaOmega (Maybe today, it is easy to get)
  * user demand
  * some files (<10Mo) for testing that cover many cases and version
I could come back to this old code with some help.

**Comment by cboulay** [comment]
Ah, I see. I have a bunch of files from an Alpha Omega MicroGuide. I'll take a look at what I can get from them using the current AO importer.

If that fails, should we / could we add an importer for the files generated by the Alpha Omega exporter tool (either .mat, .txt, etc)?

**Comment by cboulay** [comment]
I contacted Alpha Omega and was told that the spec is not publicly available and that I should use the Matlab converter or the neuroshare dll, both of which are for Windows only. I've abandoned adding support for Alpha Omega files to my processing pipeline for now.

Is there any interest in adding support in Neo for loading the .mat files that their converter generates? An `alphaomegamatio` class?

**Comment by samuelgarcia** [comment]
Same situation as some years ago. Thank you trying.
I don't think it's worth add another intermediate data file format like alphaomega.mat.
The main idea is to get data directly.

**Comment by cboulay** [comment]
I guess I will try the neuroshare api on Windows when I need to analyze these data.

**Comment by samuelgarcia** [comment]
I don't known if neuroshare offer a way to read chunk.
