### ISSUE TITLE
BlackRockIO can only load single nsX file

### ISSUE THREAD

**Issue by bjoern1001001** [NeuralEnsemble/python-neo#419]
In the latest BlackRockIO the parameter nsx_to_load in __init__ only accepts an int as parameter, so only a single nsX file can be loaded. In earlier versions multiple files could be read simultaneously which allowed for much higher flexibility and also comparison. This seems not to be possible any more.

**Comment by samuelgarcia** [comment]
Yes this is True.

Loading all nsx with the same instance made the code over complicated.

For user it will also make things more complicated at RawIO level because sampling_rate change across channel. In that case the API is a bit more verbose because you need to precise which channel_index for everything. See neuroexplorerrawio.py.

Since parse_header is quite fast I think it is not so complicated to do this:
```
reader_30k = BlackrockRawIO(filename='..', nsx_to_load=5)
reader_30k.parse_header()
sigs_30k = reader_30k.get_analogsignal_chunk()

reader_2k = BlackrockRawIO(filename='..', nsx_to_load=5)
reader_2k.parse_header()
sigs_2k = reader_2k.get_analogsignal_chunk()
```

I hope this is not too annoying.

I guess it would not be too complicated to write code to have another neo.io.BlackrockIO that is composed by several BlackrockRawIO that could render all signal at all sampling rate.

**Comment by bjoern1001001** [comment]
@JuliaSprenger and I think it would be good to have an IO that can load all signals from the specified (list or 'all') nsX files into a single neo.core.block. So if you could do this with your suggestion that would be good.
