### ISSUE TITLE
Inconsistency in writing and reading AnalogSignals with NixIO

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#545]
The order of values stored in an AnalogSignal is not preserved when writing to the Nix format and reading the data again.

Here is a minimal code example

```python
from neo import AnalogSignal,NixIO, Segment, Block
import quantities as pq
import numpy as np
import os

arr = np.array([[-0.36, -0.28, -0.36, -0.28, -0.2 , -0.12, -0.04,  0.04,  0.12, 0.2 ,  0.28,  0.36, -0.2 , -0.36, -0.28, -0.2 , -0.12, -0.04, 0.36]])

anasig = AnalogSignal(arr*pq.dimensionless,t_start=0*pq.s, sampling_rate=1*pq.Hz)

bl1 = Block()
bl1.segments.append(Segment('testseg'))
bl1.segments[0].analogsignals.append(anasig)

filename='testfile.nix'
if os.path.exists(filename):
    os.remove(filename)

with NixIO(filename) as io:
    io.write(bl1)

with NixIO(filename) as io:
    bl2 = io.read_block()

print(bl.segments[0].analogsignals[0].magnitude == bl2.segments[0].analogsignals[0].magnitude)
```

**Comment by JuliaSprenger** [comment]
It seems when loading the nix file the AnalogSignal values are sorted along axis=1.

**Comment by achilleas-k** [comment]
I've fixed the issue and I'm adding a test based on your code. PR incoming.

THANKS!

Read below for a description of the issue and solution.

---

So this isn't exactly a value sorting issue, but it is a sorting issue at its core. At first I thought it was an issue with order tracking not being enabled at the HDF5 layer, but that's something I explicitly test for in nixpy.

There are a few things of note

### The following creates an AnalogSignal with 19 channels and one sample per channel

```python
arr = np.array([[-0.36, -0.28, -0.36, -0.28, -0.2 , -0.12, -0.04,  0.04,  0.12, 0.2 ,  0.28,  0.36, -0.2 , -0.36, -0.28, -0.2 , -0.12, -0.04, 0.36]])

anasig = AnalogSignal(arr*pq.dimensionless,t_start=0*pq.s, sampling_rate=1*pq.Hz)
```

<details>
    <summary>Expand for ipython example</summary>

```python
In [1]: from neo import AnalogSignal

In [2]: import quantities as pq

In [3]: import numpy as np

In [4]: arr = np.array([[-0.36, -0.28, -0.36, -0.28, -0.2 , -0.12, -0.04,  0.04,  0.12, 0.2 ,  0.28,  0.36, -0.2 , -0.36, -0.28, -0.2 , -0.12, -0.04, 0.36]])

In [5]: AnalogSignal(arr*pq.dimensionless,t_start=0*pq.s, sampling_rate=1*pq.Hz)
Out[5]:
AnalogSignal with 19 channels of length 1; units dimensionless; datatype float64
sampling rate: 1.0
time: 0.0 to 1.0
```
</details>

### The NIXIO stores this as 19 DataArrays for length 1. Each DataArray has the same basename and an incremental numerical suffix.
<details>
  <summary>Expand for demonstration</summary>

```python
from neo import AnalogSignal, NixIO, Segment, Block
import quantities as pq
import numpy as np
import nixio as nix
from IPython.lib.pretty import pprint


arr = np.random.random((1, 19))

anasig = AnalogSignal(arr*pq.dimensionless, t_start=0*pq.s,
                      sampling_rate=1*pq.Hz)
pprint(anasig)

wb = Block()
wb.segments.append(Segment('testseg'))
wb.segments[0].analogsignals.append(anasig)

filename = 'testfile.nix'

with NixIO(filename, mode="ow") as io:
    io.write(wb)

nixfile = nix.File.open(filename, backend="h5py")
print("\n".join([da.name for da in nixfile.blocks[0].data_arrays]))
nixfile.close()
```
```
AnalogSignal with 19 channels of length 1; units dimensionless; datatype float64
sampling rate: 1.0
time: 0.0 to 1.0
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.0
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.1
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.2
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.3
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.4
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.5
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.6
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.7
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.8
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.9
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.10
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.11
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.12
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.13
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.14
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.15
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.16
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.17
neo.analogsignal.eff5b943343d43c49c78108e89b1c9cc.18
```
</details>

### During loading, the NIXIO groups data arrays by name, and foolishly sorts them lexicographically


In fact, this is done TWICE for each Group of signals, once when they're being read from the container (L1155) and once again when they're being converted to an AnalogSignal (L377) or IrregularlySampledSignal (L421):
https://github.com/NeuralEnsemble/python-neo/blob/6bda7897756be1b950efdf708bd4a1197deed86e/neo/io/nixio.py#L1155
https://github.com/NeuralEnsemble/python-neo/blob/6bda7897756be1b950efdf708bd4a1197deed86e/neo/io/nixio.py#L377
https://github.com/NeuralEnsemble/python-neo/blob/6bda7897756be1b950efdf708bd4a1197deed86e/neo/io/nixio.py#L421

This means that the order is wrong as soon as you have a signal with more than 10 channels, because `"10"` gets sorted before `"2"`.

Admittedly, this was a bit of an embarassing rookie mistake.

It turns out that the sorting is unnecessary since HDF5 guarantees that the DataArray groups are loaded based on creation order, so we can just remove all the sorting calls.
