### ISSUE TITLE
move rawio tests to tests folder

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#610]

**Comment by massich** [comment]
I was going through your codebase, and I found that `neo/rawio/tests/test_brainvisionrawio.py` and `neo/test/iotest/test_brainvisionio.py` are the same (they only change the imports). Is this what this issue is about?

apart from that, I don't fully get how are brainvision files tested. Based on what I read in [io-dev-guide](https://neo.readthedocs.io/en/latest/io_developers_guide.html#io-dev-guide), `TestBrainVisionIO` might be missing tests like this, doesn't it?
```
    def test_read_raw_protocol(self):
        reader = AxonRawIO(filename=self.get_filename_path('File_axon_7.abf'))
        reader.parse_header()

        reader.read_raw_protocol()
```

**Comment by JuliaSprenger** [comment]
Hi @massich,
I opened this issue to suggest to move the rawio tests from `neo/rawio/tests` to `neo/test/rawiotest`.

Regarding the test: For all rawios a set of generic tests is run automatically, because the format specific raw IOs (like `TestBrainVisionRawIO`) are inheriting from `BaseTestRawIO`. It is recommended, but optional, to extend this by adding explicit tests like the one you list. So if you have format specific tests in mind or already implemented, don't hesitate to open a PR.

**Comment by samuelgarcia** [comment]
Hi @massich
the ```read_raw_protocol``` is very specific to axonrawio.

As Julia said common test are run by inheritence:
  * BaseTestRawIO for all neo.rawio classes
  * BaseTestIO for all neo.io classes

Basically they:
  * download files from gin
  * run all methods that theses API (io and rawio) expose and test that output is consitent.

To understand have a look in:
  * python-neo/neo/test/iotest/common_io_test.py
  * python-neo/neo/rawio/tests/common_rawio_test.py
  * python-neo/neo/rawio/tests/rawio_compliance.py

Sam
