### ISSUE TITLE
NixIOFr is ignoring annotations

### ISSUE THREAD

**Issue by JuliaSprenger** [NeuralEnsemble/python-neo#625]
Using the NixIOFr annotations of neo objects are not loaded, eg. the code below raises an `AssertionError`.
```python
from neo import NixIO, NixIOFr, Block

annotations = {'my_custom_annotation': 'hello block'}

with NixIO(filename) as io:
    bl = Block(**annotations)
    io.write_block(bl)

with NixIOFr(filename) as io:
    bl = io.read_block()
    assert len(bl.annotations) == len(annotations)
```

This leads to the unintentional merge of multiple AnalogSignals, when being loaded as they are considered to be the same object and merged into a single AnalogSignal object

**Comment by hkchekc** [comment]
@JuliaSprenger Hi, thanks for telling. I will see how to fix it under the baserawio annotation generating framework.

On the other hand, I don't really understand how it leads to merge of multiple AnalogSignals. Can you show be some code? I think it may be due to our default signal-grouping-mode is group all signals in same channel?

**Comment by hkchekc** [comment]
Some fixes is in #629

**Comment by samuelgarcia** [comment]
## Note

**signal_group_mode** change the annotations behavior in read_block for all IOs depending on **'split-all'** or **'group-by-same-units'**.

This is because in rawio annotations are by channels.

So, this is mono channel signal with all annotations:
```python
anasig = reader.read_block(signal_group_mode='split-all').segments[0].analosignals[0]
```

and this is a multi channel signal without by-channel annotations because it is a channel bundle:
```python
anasig = reader.read_block(signal_group_mode='group-by-same-units').segments[0].analosignals[0]
```



Since the new array annotation features, annotations by channels will be back with **signal_group_mode='group-by-same-units'** in next version with new lazy mode, I am working on it here #461.
And so the default will be **signal_group_mode='group-by-same-units'** for all IOs without the lost of by-channels annotations.

**Comment by JuliaSprenger** [comment]
The example above still fails, but due to additional `nix_name` annotations being introduced when writing data to nix and not due to the original issue. An updated fair comparison would be

```python
with NixIO(filename,'ow') as io:
    bl0 = Block(**annotations)
    io.write_block(bl0)

with NixIOFr(filename) as io:
    bl1 = io.read_block()
    assert len(bl0.annotations) == len(bl1.annotations)
```

The original issue is therefore solved. A follow up issue is #740.
