### ISSUE TITLE
Improve `get_io()`

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#628]
Since the same filename extension may be used by multiple formats (this is particularly true for `.h5` and `.txt`), `get_io()` should be more sophisticated, e.g. try all possible IOs in turn until one works.

**Comment by zm711** [comment]
Fixed by combo of #1190 (`list_candidate_ios`-function which returns all possible ios so the user can decide for the correct one) and #1297 (`get_io` functionality improved and tries to return the most likely ios based on counting). Reopen if you were hoping for something different than these functionalities.
