### ISSUE TITLE
[Question] Plexon file with different sampling rates

### ISSUE THREAD

**Issue by cmmoenne** [NeuralEnsemble/python-neo#658]
I was wondering if there is a way to read Plexon plx files with different sample rates (40 KHz and 1 KHz) or a workaround to only read the channels with a specific sample rate only, so first I read the 40 KHz channels and then the 1 KHz channels.

So far, I get the error:
```
AssertionError: Signal do not have the same sampling rate
```

**Comment by samuelgarcia** [comment]
In the current implementation to make the code simple, this is not possible.

If you have a strong need to read this multi sampling rate file I can help you make a patch. The neo.rawio and neo.io API allow this but make each io more difficults to code because teh readers have to deal with several channel groups.

**Comment by cmmoenne** [comment]
As the datasets aren't mine, first I'm going to ask if they can convert the datasets to make it easier to read the files.

Thanks for the reply!
