### ISSUE TITLE
Duplicate neo_name and nix_name when saving object to new nix file

### ISSUE THREAD

**Issue by rgutzen** [NeuralEnsemble/python-neo#694]
Neo objects are assigned unique identifiers (_neo_name_, _nix_name_) when saved with the NixIO (see #331). However, because these identifiers are required to be unique, this leads to an error when a loaded neo object is saved to a different file.

**Minimal example:**
```
import neo

with neo.NixIO('/path/to/file.nix', 'ro') as io:
    img_block = io.read_block()

# Perform some edit which keeps the annotations 'neo_name' and 'nix_name'
# of the block and/or its child objects.

with neo.NixIO('/path/to/new_file.nix', 'ow') as io:
    io.write(img_block)
```
neo: 0.7.2
nixio: 1.5.0b1

**Error message:**
`DuplicateName: Duplicate name - names have to be unique for a given entity type & parent. (create_property)`

A workaround is to manually delete the respective annotations before saving, but since loading an object and saving it to another file is a rather common operation, this probably should be handled by the NixIO itself. A solution, for example, could be to have a boolean argument _ignore_duplicate_names_ in the write function or a check which tests whether the object is written to an existing or a new file.

**Comment by achilleas-k** [comment]
This is strange.  At first I thought it was straightforward and caused by the reasons you described, but on further inspection it's a bit more puzzling.  Here's what confuses me:
- It's certainly not an issue with existing objects in a file, since you're writing to a newly created one.
- It doesn't seem to be an issue with duplicating objects and writing them in the file, because the exception wasn't raised by a data object creation method, but a property (metadata/annotation) creation.

This makes it even more confusing because for `create_property()` to trigger the exception, it means there were multiple annotations with the same name, which shouldn't be possible.

This makes me think there's a bug in the Neo NIXIO where it tries to write the same annotation twice or the same metadata section is used for multiple objects causing a conflict.

Do you have the full traceback of the exception you got?

**Comment by achilleas-k** [comment]
Ok I managed to reproduce with the following extremely simple sample:
```python
import neo

blk = neo.Block()

# write first file
with neo.NixIO("first.nix", "ow") as io:
    io.write(blk)

# read first file and write it to second
with neo.NixIO("first.nix", "ro") as io:
    rblk = io.read_block()

with neo.NixIO("second.nix", "ow") as io:
    io.write(rblk)
```

**Comment by achilleas-k** [comment]
Ok, got it.  PR coming in a bit.  THANKS!
