### ISSUE TITLE
AttributeError: 'list' object has no attribute 'segments'

### ISSUE THREAD

**Issue by McDr** [NeuralEnsemble/python-neo#762]
Trying to run an example from the Neo Core documentation (only updated urllib import): 

```
from neo.io import AxonIO
import urllib.request
url = "https://web.gin.g-node.org/NeuralEnsemble/ephy_testing_data/raw/master/axon/File_axon_3.abf"
filename = './test.abf'
urllib.request.urlretrieve(url, filename)

r = AxonIO(filename=filename)
bl = r.read() # read the entire file > a Block
print(bl)
#print(bl.segments) # child access
for seg in bl.segments:
    print(seg)
    print(seg.block) # parent access
```

This leads to the error: 

> Traceback (most recent call last):
> [<neo.core.block.Block object at 0x000001BCA508CE48>]
>   File "C:/Users/mattm/PycharmProjects/OrganoidMEA/testing.py", line 10, in <module>
>     print(bl.segments) # child access
> AttributeError: 'list' object has no attribute 'segments'
> 
> Process finished with exit code 1

**Comment by shw3ta** [comment]
Any updates on this?

**Comment by JuliaSprenger** [comment]
Hi @shw3ta! Thanks for the reminder about this.
The actual issue here is that `r.read()` returns a list of Block objects and not a single Block. So if you change line 8 of the example above to `bl = r.read()[0]` then you are actually extracting a neo Block and the example should run smoothly. Alternatively, you can also use the `r.read_block(...)` function instead as this one loads only a single block.

**Comment by shw3ta** [comment]
Thank you, @JuliaSprenger. I'm only just acquainted with neo, this suggestion helped.

**Comment by apdavison** [comment]
#859 fixes the mistake in the example code from the core documentation, and adds a docstring to the `read()` method.
