### ISSUE TITLE
Read digital channels from rhd

### ISSUE THREAD

**Issue by luiztauffer** [NeuralEnsemble/python-neo#792]
Hi, I’m using `IntanIO` to read form `rhd` files, which works well but does not read digital channels. Am I missing something or is this still to-be-implemented?

Just as a reference, Intantech provides python scripts that read those files and extract basically everything in nice dictionaries: http://intantech.com/downloads.html?tabSelect=Software

**Comment by Ashkees** [comment]
Hi.  I am also interested in this feature if it becomes available.  Thanks!

**Comment by samuelgarcia** [comment]
Hi all.
I am the autor of this IO but I never use it.
Reading this
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/intanrawio.py#L522
suggest that it is implemented at header parsing level but thoses channel are not exposed to 
_get_analogsignal_chunk and not expose in the header['signal_channels']
If someone have time to do it it would be great.
Do you plan to have expose thoeses channels as analogsignal (with 0 and 1) or via events (that would need a full read of the entire file) ?

**Comment by Ashkees** [comment]
For me, either an analogsignal or events would be fine.  If I had it as as analogsignal, most likely I would then convert it into an events, but this should be straightforward.

**Comment by CodyCBakerPhD** [comment]
Some progress towards this in #1249

**Comment by bendichter** [comment]
@CodyCBakerPhD , @luiztauffer , #1249 is now merged. What are the next steps here?

**Comment by CodyCBakerPhD** [comment]
@luiztauffer what project did you need this for? (If you can remember) - this issue can likely be closed

A new release of neo would be great @samuelgarcia 

I suppose confirmation that it works in SI to close https://github.com/SpikeInterface/spikeinterface/issues/1876 is the small 'next step'

Otherwise, @weiglszonja has a current project that needs this so they will be making the data interface on NeuroConv: https://github.com/catalystneuro/neuroconv/issues/519
