### ISSUE TITLE
Neuralynx loader output for a given file differs depending on what other files are present in folder

### ISSUE THREAD

**Issue by mvdm** [NeuralEnsemble/python-neo#814]
When loading a Neuralynx data file, the timestamps assigned by neo depend on what other files are present in the same folder. 

For instance, loading a .ntt file with no other files present gives a first timestamp of 0.0 s, but loading that same file with some .ncs files also present gives a first timestamp of ~0.12 s.

Minimal working example [here](https://github.com/vandermeerlab/data-formats/blob/master/neo-nept-loading.ipynb).

I would consider this behavior undesirable because of the considerable potential for inconsistencies. The same code can now give different results depending on what files are present at the time of loading, and it is unclear how any timestamped data from different sources (e.g. spike sorters) could be aligned with the neo timestamps.

I would prefer an option, maybe even the default, to have the loader output the timestamps actually reported by the Neuralynx recording system.

**Comment by samuelgarcia** [comment]
So the reason more due to the neuralynx format than neo implementation.

In neo we have the concept of t_start.

In neo t_start for an AnalogSignal is the timestamp of the first sample.

For SpikeTrain (or Event) :  t_start (or t_stop) have another meaning : it give boudaries to a train of event or spike.
It can be usefull when the absolute recording start is 1000s and the first spike is 1001s.

In the case of of neuralynx, the t_start/t_stop is hold only by the ncs file (analogsignal file) without it we don't have accces to this t_start so we put 0.s the best option would to raise an error when ncs is not availiable in that case we put 0. 
In neuralynx, timestamps of spikes are relative to this t_start. So when we have it (chen ncs is present) we use it. And without, we put 0.

I agree we could put a kargs and/or a wrning for that.

See
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuralynxrawio.py#L206-L240

**Comment by mvdm** [comment]
Yes, the concept of t_start (and t_end) is important for things like calculating firing rates, as you point out. But these boundaries can be loaded or specified, in principle, without changing any of the timestamps. In other words, t_start could be some nonzero value.

Is it a neo architecture decision to force t_start to be 0? Or could there be an option to have it be the actual Neuralynx recording start time? (which incidentally is stored more accurately in the Events.nev file, but can be approximated with ncs timestamps as you say).

**Comment by samuelgarcia** [comment]
It is neuralynx specific.
I think that spike timestamps are clock internal clock ticks.
And so timestamps depend of the very global t_start which itself depend on other files.
I will check the code.

**Comment by samuelgarcia** [comment]
We have maybe a bug here.
@JuliaSprenger : do you remember why does the self.global_t_start is used here
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuralynxrawio.py#L344
it is related to this
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuralynxrawio.py#L206-L240

**Comment by samuelgarcia** [comment]
OK I anderstand.
We have a concept of global t_start inside this IO which is the very timestamp accros all object (sigs, event, spike) and accros all segments.
This global_t_start is hidden externaly (begining of recording and set to 0s)

It appear here that signals starts 0.12s before the first spike.
In short there is NO t_start in the ntt file, so the first spike is the t_start which is bad I admit it.
Abscence of ncs should raise an error or a warning by default.

@JuliaSprenger : what do you think ?

**Comment by JuliaSprenger** [comment]
Yes, in this IO all data is aligned according to the first sample recorded to have the whole dataset relative to t=0. In case of a only nse or ntt this is the first spike, since these files don't contain a t_start. In case of an ncs being present, this is the first sample.
This is what is causing the first spike being aligned to different times depending on the reference files being present. I agree this should be definitely documented and probably be an option of this IO that can be selected by the user.
However, I don't agree to raise an error when no ncs file is present, since in some cases these files might not be available due to their (potentially) large size. I think a warning is the better choice here.

**Comment by mvdm** [comment]
OK, I understand that the difference in output that started this issue arises from an underlying goal to find the first recorded sample across all data types and files in the data set and designate that sample t = 0. I agree a warning if no ncs or nev file is present would be helpful to alert the user that under these conditions, t = 0 likely will not correspond to the start of the recording.

However: is having a t = 0 sample a requirement for other neo components to work? I do not think we would be able to use neo for our purposes unless there is an option to not realign the times (i.e. simply return the timestamps as stored in the nlx files). Thanks for both your input!

**Comment by samuelgarcia** [comment]
You can have access to the true time stamps with the neo.rawio layer and not the neo.io layer.

```python
reader = neo.rawio.NeuralynxRawIO(dirname='yepyepyep')
reader.parse_header()
print(reader)

spike_timestamps = reader.spike_timestamps(block_index=0, seg_index=0, unit_index=0)

```

Have a look to:  https://neo.readthedocs.io/en/stable/rawio.html

@JuliaSprenger : yes the warning sounds better.

**Comment by JuliaSprenger** [comment]
@mvdm Can you test the new 'keep_original_times' feature of the NeuralynxIO by installing the current master? I hope this solves your issue.

**Comment by mvdm** [comment]
@JuliaSprenger: I tested the 'keep_original_times' feature on our data and the loader now returns the expected timestamps (without attempting to align to zero). I also did a few informal tests on the output, such as visually inspecting the histogram of differences between timestamps, and all looks good. Thank you!
