### ISSUE TITLE
Consistent string formatting

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#857]
As part of the cleanup for v1.0 we should make the string formatting consistent across the code base.

Currently there is a mixture of `%` and `.format()`.

By that time, we should only be supporting versions of Python that support f-strings, so I would suggest we use those throughout.

**Comment by zm711** [comment]
Just to address what I've done in #1396. 

* So docstrings can not be f-strings and as of my reading this is not possible bug report and discussion about why this isn't happening [here](https://bugs.python.org/issue28739). So docstrings will remain %.
* There is one conversion to what I think is hex that still needs to be fixed. There is one if-else that would require some pretty confusing nested f-strings to work (and I'm not sure of minimum version of python) so maybe we hold off and leave that as a format since it will be clearer.
