### ISSUE TITLE
Nix IO bloated file

### ISSUE THREAD

**Issue by phifisch** [NeuralEnsemble/python-neo#866]
I want to save the results of my analysis scripts in a format that is more reliable in the future than a simple pickle file. As I understand that Nix is the best supported, I tried that, but it results in incredibly bloated files (not to mention that it takes hours to write them). To give you an idea: As a pickle file, it takes about 100 MB, in the neo .mat format it is 85 MB, whereas nix runs up to 8 GB. Since mat-files don't support all the details of my metadata, I would prefer to try nix. Any ideas on why this bloat occurs, or how I could find out more about it?
Perhaps I can try to create a minimal example that demonstrates this behavior.

**Comment by phifisch** [comment]
Thanks for the reply. Yes, both of these requirements are met. I used the neo commit 4e903124e66123746da721211ea00dd70b99434b (only 1 commit behind of current, which seems to be unrelated to this issue). I have one block with 85 segments with 1 AnalogSignal each.

**Comment by JuliaSprenger** [comment]
@achilleas-k Any ideas for further improvements? Does the latest beta version including repacking / removing of unlinked data chunks already or would this be another potential source for the bloat?

**Comment by achilleas-k** [comment]
Storage optimisation changes were included in v1.5.0b5.  From the description of the file (85 AnalogSignals) it seems like 8 GB is extremely large, even before we fixed the allocation issue.

The main source of the problem was metadata properties: Each annotation would be allocated much more space than it needed which resulted in the unnecessarily large files.  Is there a lot of metadata (annotations) attached to each signal and segment?

**Comment by phifisch** [comment]
Each of the segments' unique analogsignals has a few annotations, but not that many. To be precise it is something like
`{'boundaries': array([1173615, 1190863], dtype=int64), 'meanValue': 0.3989286825268318, 'samplingRate': 10000.0, 'numel': 17248}` . 
I am not really familiar with the HDF5 format, but perhaps the API does some sort of duplicate key checking when writing, leading to a long duration when writing and adding "unnecessary" bloat? (I seem to remember a PR that was mentioning something along those lines, but can't find it again...) 
On the other hand, the block itself holds a lot of annotations, including some derived from python dicts using int and float as keys. I know that the latter causes trouble for the MatlabIO (because struct fields cannot be numbers), but the consequences are very different. Do you think that might be part of the problem here as well?

**Comment by achilleas-k** [comment]
> On the other hand, the block itself holds a lot of annotations, including some derived from python dicts using int and float as keys.

The keys shouldn't be an issue, but the number of annotations might be.  In your first message you offered to create a minimal example to demonstrate.  I think that would help.  Perhaps there are some edge cases we haven't considered, or even something fundamental that I missed.

**Comment by phifisch** [comment]
So, after testing several slices of data, IMHO there is something more fundamental going on, or perhaps I misunderstood how to use the IO properly. The chunks of data that are contained in each segment has the size 103488 data points (6x17248) of float64 type, resulting in about 800 KB per segment. 
The block.annotations alone take up about 14 MB both as a nix- or mat-file. When we add a single segment to the files, their size grows to about 90 MB for nix, and only 15 MB for mat (as expected by segment size). Removing all annotations from the segment has only a marginal effect.
Adding more segments (different but same size) pretty much adds always the same amount to the file size.
I will append the two simplest cases as mat-files, sou you can inspect them (remove the '.txt' of course). I'll also add the part my code that concerns the IO without the rest of the analysis class to keep it simple.
For now I'll stick to mat-files, but if we can figure this out, it would be great for hte future. I'm willing to contribute as much as I can.

[myNeoIO_minimal.py.txt](https://github.com/NeuralEnsemble/python-neo/files/5247488/myNeoIO_minimal.py.txt)
[example_1segment.neomat.txt](https://github.com/NeuralEnsemble/python-neo/files/5247413/example_1segment.neomat.txt)
[example_onlyAnnotations.neomat.txt](https://github.com/NeuralEnsemble/python-neo/files/5247414/example_onlyAnnotations.neomat.txt)

**Comment by achilleas-k** [comment]
I think I found the cause of the problem.  The NIXIO splits 2-dimensional signals into multiple 1-dimensional DataArrays.  It's a little difficult to describe the reasons in detail briefly, but generally it's done to keep the structure of the objects in the file _logically_ consistent with respect to how NIX handles tagging (points and/or regions of interest).
The split is done so that each DataArray represents a signal and all arrays share the same time dimension.  In Neo AnalogSignals, dimension 0 is time and dimension 1 is channel index.  So for a given AnalogSignal `asig` in Neo, taking `asig[0]` returns the first value of each signal (at `t=0`) and taking `asig[:, 0]` returns the entirety of the first signal (it actually returns an AnalogSignal object).

It seems that, in your minimal example at least, the data that's placed in the AnalogSignal is transposed (this is a guess on my part, so please confirm).  I made some edits to your script for testing:
[script.zip](https://github.com/NeuralEnsemble/python-neo/files/5261240/script.zip)

The important change is L51:
```python
ch = np.transpose(ch)
```
where I transpose the channel data before creating the AnalogSignal.
After creating the object, I use the IPython pretty representation which Neo objects implement to show some very handy information about.  With the transpose, the pretty print shows:
```
AnalogSignal with 6 channels of length 17248; units V; datatype float64
name: 'flyIndex 0,groupIndex 0,flying 1'
annotations: {'boundaries': array([1173615, 1190863]),
'meanValue': 0.3989286825268318,
'samplingRate': 10000.0,
'numel': 17248}
sampling rate: 10000.0 Hz
time: 0.0 s to 1.7248 s
```
Is this correct?

If we remove the transpose line, it instead becomes
```
AnalogSignal with 17248 channels of length 6; units V; datatype float64
name: 'flyIndex 0,groupIndex 0,flying 1'
annotations: {'boundaries': array([1173615, 1190863]),
'meanValue': 0.3989286825268318,
'samplingRate': 10000.0,
'numel': 17248}
sampling rate: 10000.0 Hz
time: 0.0 s to 0.0006 s
```

You'll also notice the lines in main at the bottom where I print the number and shape of the DataArrays in the NIX file:
```python
    blk = nf.blocks[0]
    print(f"File has {len(blk.data_arrays)} data arrays")
    print(f"First data array has shape {blk.data_arrays[0].shape}")
```

**Without** transposing, this prints:
```
File has 17248 data arrays
First data array has shape (6,)
```
and the NIX file size grows to 89 MiB, which is consistent with your previous message.

**With** the transposing of the signal, this prints:
```
File has 6 data arrays
First data array has shape (17248,)
```
and the NIX file size is 15 MiB, which is much closer to what we expect.

The cause of the size bloat is (likely) due to object size overhead.  Some metadata is duplicated.  Annotations are shared between all arrays, but each array requires its own dimension descriptors, for instance.  17k extra objects certainly adds up.  There might also be some issue with the arrays being so small that HDF5's automatic chunk sizing preallocates a bit of extra space for resizing, which also adds up over 17k objects.

We made some change recently in NIX that makes tagging more flexible.  This solves the issue we had that required DataArrays to be split in order to keep the file consistent.  I was hoping to make the change once we had a proper release of 1.5.

For now though, if I'm right about your signal shapes, transposing the channel data should make your files much smaller.  Let me know how it goes.

**Comment by phifisch** [comment]
That is exactly what happened! And taking the transpose solves the issue. Now the size in the NIX format is in between the mat- and pickle-file (about 20% more than the matfile, which is fine). I was not aware that NEO makes assumptions about the array shape, let alone NIX. 
If I understand you right, the change you were planning to do would solve this issue already anyways. In that case there is nothing more to do in this thread.

**Comment by phifisch** [comment]
Not to forget, thanks a lot!

**Comment by achilleas-k** [comment]
> That is exactly what happened! And taking the transpose solves the issue. Now the size in the NIX format is in between the mat- and pickle-file (about 20% more than the matfile, which is fine). I was not aware that NEO makes assumptions about the array shape, let alone NIX.

NIX itself doesn't make assumptions about the dimensions, the user sets defines the meaning of each dimension of an array, but since Neo does, the Neo-NIXIO relies on that assumption to set the dimensionality.

> If I understand you right, the change you were planning to do would solve this issue already anyways. In that case there is nothing more to do in this thread.

Great!

> Not to forget, thanks a lot!

Happy to help!  :)
