### ISSUE TITLE
IO for Neuropixels data

### ISSUE THREAD

**Issue by rjurkus** [NeuralEnsemble/python-neo#909]
There is a lot of interest in having an IO developed to load Neuropixels data. In the next few days we should have a small dataset that could be used for testing (SpikeGLX/Kilosort2/Phy). I think would be good to coordinate the development of prototype IO so that it fits Neo standard. 

@samuelgarcia , I have a very basic loading routine for getting Kilosort2/Phy spike clusters into Neo, using a larger dataset provided by a researcher. Perhaps we could build on this and get a prototype IO going?

**Comment by samuelgarcia** [comment]
Have you seen #896 ?
It is done. But the PR need to be reviewed.

And I have a small test files here : 
https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/spikeglx

I will be happy with feedback.

**Comment by samuelgarcia** [comment]
And about the kilosort/phy into we already have this in spikeextractor.
I want to port everyhting into neo.
Help will appreciated of course!!

**Comment by Qkley** [comment]
@JuliaSprenger mentioned the SpikeGLX today. We will get some SpikeGLX files from the researcher which I could use to have a look at the implementation.
Regarding kilosort/phy perhaps we could combine forces and make a short (i.e. half-day) hackathon in December to work on the porting of the routines? Perhaps sometime during the week of the 7th of December or, failing that, a week later? We were discussing this today already. This way we would be working with the same goal in mind.

**Comment by samuelgarcia** [comment]
Cool. Give me feedback on implementation.
This format is quite simple.
My plan is to merge soon.
And then you will be able to improve it.

For the hackaton: yes yes and yes.
I would propose also spikeinterface team to join use.
@colehurwitz @alejoe91 would you join use ?

We could try to integrate in neo many sorters output : kilosrt1, kilosrt2, kilosrt2.5, spykingcircus, tridesclous, ironclust.
It is quite simple because it is only for spikes and the API is quite similar finally for spikes).
If we are 5 : regi, julia, allesio, cole and me. Then we could make 5 io the same afternoon.

**Comment by Qkley** [comment]
Regarding the hackathon, perhaps we should aim a bit smaller - just the kilosort and phy? I have not made an IO before so it would be a learning experience. Moreover, the researchers would be interested in joining too. I think this would be quite helpful, as, for example, we will need to figure out what exactly do we take from kilosort and phy outputs since I do not think that absolutely everything is needed.

**Comment by samuelgarcia** [comment]
No lets be ambitious.
Alessio and Cole never did neo.rawio.
You could all make one.
Julia+me could supervise and also make another one.

**Comment by JuliaSprenger** [comment]
I agree with @Qkley, this might be a bit too ambitious, but we can start with the 5-parallel IOs plan and downscale if it doesn't work.

**Comment by samuelgarcia** [comment]
No. No.
All the mentioned people are super super efficient dev.
For sure, the goal is manageable.

**Comment by colehurwitz** [comment]
I would be happy to join the hackathon. I like the ambition!

**Comment by samuelgarcia** [comment]
Cole : this is super cool.
Lets choose a date in private : I will send an email.

@alejoe91 would like also to join but he is a shy guy.
He need encouragement : Alessio, Alessio, Alessio!

**Comment by alejoe91** [comment]
Ahahah I'll join the hackathon too :)

**Comment by samuelgarcia** [comment]
#896 Done.

**Comment by TomBugnon** [comment]
Hi all,
Thanks a lot for the SGLX reader implementation! Is there any progress (happening or to be expected) regarding support of kilosort/phy data?
Best, Tom

**Comment by samuelgarcia** [comment]
Glade, it helps.
phyio have been merge https://github.com/NeuralEnsemble/python-neo/pull/928
phyio is the natural kilosort output.
You be able to usse it.
